"""módulo de políticos: tabelas pol_*

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-06 18:53:01.460913
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pol_politico",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fonte", sa.String(length=20), nullable=False),
        sa.Column("id_fonte", sa.String(length=40), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column("partido", sa.String(length=30), nullable=True),
        sa.Column("cargo", sa.String(length=30), nullable=False),
        sa.Column("uf", sa.String(length=2), nullable=False),
        sa.Column("cod_ibge", sa.Integer(), nullable=True),
        sa.Column("situacao", sa.String(length=80), nullable=True),
        sa.Column("em_exercicio", sa.Boolean(), nullable=True),
        sa.Column("legislatura", sa.Integer(), nullable=True),
        sa.Column("mandato_inicio", sa.Date(), nullable=True),
        sa.Column("mandato_fim", sa.Date(), nullable=True),
        sa.Column("eleicao_ano", sa.Integer(), nullable=True),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("url_pagina", sa.Text(), nullable=True),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fonte", "id_fonte", "cargo", name="uq_pol_politico"),
    )
    op.create_index(op.f("ix_pol_politico_cargo"), "pol_politico", ["cargo"], unique=False)
    op.create_index(op.f("ix_pol_politico_cod_ibge"), "pol_politico", ["cod_ibge"], unique=False)
    op.create_index(op.f("ix_pol_politico_nome"), "pol_politico", ["nome"], unique=False)
    op.create_index(
        op.f("ix_pol_politico_resposta_id"), "pol_politico", ["resposta_id"], unique=False
    )
    op.create_index(op.f("ix_pol_politico_uf"), "pol_politico", ["uf"], unique=False)
    op.create_table(
        "pol_comissao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("politico_id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("sigla", sa.String(length=40), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("casa", sa.String(length=10), nullable=True),
        sa.Column("participacao", sa.String(length=60), nullable=True),
        sa.Column("data_inicio", sa.Date(), nullable=True),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["politico_id"], ["pol_politico.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pol_comissao_politico_id"), "pol_comissao", ["politico_id"], unique=False
    )
    op.create_index(
        op.f("ix_pol_comissao_resposta_id"), "pol_comissao", ["resposta_id"], unique=False
    )
    op.create_table(
        "pol_emenda",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo_emenda", sa.String(length=40), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("tipo_emenda", sa.String(length=120), nullable=True),
        sa.Column("transferencia_especial", sa.Boolean(), nullable=False),
        sa.Column("autor", sa.String(length=200), nullable=True),
        sa.Column("nome_autor", sa.String(length=200), nullable=True),
        sa.Column("numero_emenda", sa.String(length=40), nullable=True),
        sa.Column("localidade_gasto", sa.String(length=200), nullable=True),
        sa.Column("cod_ibge_destino", sa.Integer(), nullable=True),
        sa.Column("funcao", sa.String(length=120), nullable=True),
        sa.Column("subfuncao", sa.String(length=120), nullable=True),
        sa.Column("valor_empenhado", sa.Numeric(), nullable=True),
        sa.Column("valor_liquidado", sa.Numeric(), nullable=True),
        sa.Column("valor_pago", sa.Numeric(), nullable=True),
        sa.Column("valor_resto_inscrito", sa.Numeric(), nullable=True),
        sa.Column("valor_resto_cancelado", sa.Numeric(), nullable=True),
        sa.Column("valor_resto_pago", sa.Numeric(), nullable=True),
        sa.Column("politico_id", sa.Integer(), nullable=True),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["politico_id"], ["pol_politico.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_emenda"),
    )
    op.create_index(op.f("ix_pol_emenda_ano"), "pol_emenda", ["ano"], unique=False)
    op.create_index(
        op.f("ix_pol_emenda_cod_ibge_destino"), "pol_emenda", ["cod_ibge_destino"], unique=False
    )
    op.create_index(op.f("ix_pol_emenda_nome_autor"), "pol_emenda", ["nome_autor"], unique=False)
    op.create_index(op.f("ix_pol_emenda_politico_id"), "pol_emenda", ["politico_id"], unique=False)
    op.create_index(op.f("ix_pol_emenda_resposta_id"), "pol_emenda", ["resposta_id"], unique=False)
    op.create_table(
        "pol_presenca",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("politico_id", sa.Integer(), nullable=False),
        sa.Column("id_evento", sa.String(length=20), nullable=False),
        sa.Column("data_hora_inicio", sa.DateTime(), nullable=False),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["politico_id"], ["pol_politico.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("politico_id", "id_evento", name="uq_pol_presenca"),
    )
    op.create_index(
        op.f("ix_pol_presenca_data_hora_inicio"), "pol_presenca", ["data_hora_inicio"], unique=False
    )
    op.create_index(
        op.f("ix_pol_presenca_politico_id"), "pol_presenca", ["politico_id"], unique=False
    )
    op.create_index(
        op.f("ix_pol_presenca_resposta_id"), "pol_presenca", ["resposta_id"], unique=False
    )
    op.create_table(
        "pol_proposicao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("politico_id", sa.Integer(), nullable=False),
        sa.Column("id_fonte", sa.String(length=40), nullable=False),
        sa.Column("sigla_tipo", sa.String(length=20), nullable=True),
        sa.Column("numero", sa.String(length=20), nullable=True),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("ementa", sa.Text(), nullable=True),
        sa.Column("data_apresentacao", sa.Date(), nullable=True),
        sa.Column("autoria", sa.Text(), nullable=True),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("url_pagina", sa.Text(), nullable=True),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["politico_id"], ["pol_politico.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("politico_id", "id_fonte", name="uq_pol_proposicao"),
    )
    op.create_index(op.f("ix_pol_proposicao_ano"), "pol_proposicao", ["ano"], unique=False)
    op.create_index(
        op.f("ix_pol_proposicao_politico_id"), "pol_proposicao", ["politico_id"], unique=False
    )
    op.create_index(
        op.f("ix_pol_proposicao_resposta_id"), "pol_proposicao", ["resposta_id"], unique=False
    )
    op.create_table(
        "pol_votacao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("politico_id", sa.Integer(), nullable=False),
        sa.Column("id_votacao", sa.String(length=40), nullable=False),
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("voto", sa.String(length=60), nullable=False),
        sa.Column("voto_descricao", sa.String(length=120), nullable=True),
        sa.Column("orgao", sa.String(length=40), nullable=True),
        sa.Column("materia", sa.String(length=80), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["politico_id"], ["pol_politico.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("politico_id", "id_votacao", name="uq_pol_votacao"),
    )
    op.create_index(op.f("ix_pol_votacao_data"), "pol_votacao", ["data"], unique=False)
    op.create_index(
        op.f("ix_pol_votacao_politico_id"), "pol_votacao", ["politico_id"], unique=False
    )
    op.create_index(
        op.f("ix_pol_votacao_resposta_id"), "pol_votacao", ["resposta_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pol_votacao_resposta_id"), table_name="pol_votacao")
    op.drop_index(op.f("ix_pol_votacao_politico_id"), table_name="pol_votacao")
    op.drop_index(op.f("ix_pol_votacao_data"), table_name="pol_votacao")
    op.drop_table("pol_votacao")
    op.drop_index(op.f("ix_pol_proposicao_resposta_id"), table_name="pol_proposicao")
    op.drop_index(op.f("ix_pol_proposicao_politico_id"), table_name="pol_proposicao")
    op.drop_index(op.f("ix_pol_proposicao_ano"), table_name="pol_proposicao")
    op.drop_table("pol_proposicao")
    op.drop_index(op.f("ix_pol_presenca_resposta_id"), table_name="pol_presenca")
    op.drop_index(op.f("ix_pol_presenca_politico_id"), table_name="pol_presenca")
    op.drop_index(op.f("ix_pol_presenca_data_hora_inicio"), table_name="pol_presenca")
    op.drop_table("pol_presenca")
    op.drop_index(op.f("ix_pol_emenda_resposta_id"), table_name="pol_emenda")
    op.drop_index(op.f("ix_pol_emenda_politico_id"), table_name="pol_emenda")
    op.drop_index(op.f("ix_pol_emenda_nome_autor"), table_name="pol_emenda")
    op.drop_index(op.f("ix_pol_emenda_cod_ibge_destino"), table_name="pol_emenda")
    op.drop_index(op.f("ix_pol_emenda_ano"), table_name="pol_emenda")
    op.drop_table("pol_emenda")
    op.drop_index(op.f("ix_pol_comissao_resposta_id"), table_name="pol_comissao")
    op.drop_index(op.f("ix_pol_comissao_politico_id"), table_name="pol_comissao")
    op.drop_table("pol_comissao")
    op.drop_index(op.f("ix_pol_politico_uf"), table_name="pol_politico")
    op.drop_index(op.f("ix_pol_politico_resposta_id"), table_name="pol_politico")
    op.drop_index(op.f("ix_pol_politico_nome"), table_name="pol_politico")
    op.drop_index(op.f("ix_pol_politico_cod_ibge"), table_name="pol_politico")
    op.drop_index(op.f("ix_pol_politico_cargo"), table_name="pol_politico")
    op.drop_table("pol_politico")
    # ### end Alembic commands ###
