"""politicos: pendencias de cargos e cota parlamentar

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-06 19:44:31.660395
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pol_pendencia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fonte", sa.String(length=20), nullable=False),
        sa.Column("eleicao_ano", sa.Integer(), nullable=False),
        sa.Column("cargo", sa.String(length=30), nullable=False),
        sa.Column("uf", sa.String(length=2), nullable=False),
        sa.Column("cod_ibge", sa.Integer(), nullable=True),
        sa.Column("motivo", sa.Text(), nullable=False),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fonte",
            "eleicao_ano",
            "cargo",
            "uf",
            "cod_ibge",
            name="uq_pol_pendencia",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_pol_pendencia_cod_ibge"), "pol_pendencia", ["cod_ibge"], unique=False)
    op.create_index(
        op.f("ix_pol_pendencia_resposta_id"), "pol_pendencia", ["resposta_id"], unique=False
    )
    op.create_table(
        "pol_despesa_cota",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("politico_id", sa.Integer(), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("mes", sa.Integer(), nullable=False),
        sa.Column("linha", sa.Integer(), nullable=False),
        sa.Column("categoria", sa.String(length=200), nullable=False),
        sa.Column("especificacao", sa.String(length=200), nullable=True),
        sa.Column("fornecedor", sa.String(length=300), nullable=True),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("pessoa_fisica", sa.Boolean(), nullable=False),
        sa.Column("numero_documento", sa.String(length=100), nullable=True),
        sa.Column("tipo_documento", sa.String(length=4), nullable=True),
        sa.Column("data_emissao", sa.Date(), nullable=True),
        sa.Column("valor_documento", sa.Numeric(), nullable=True),
        sa.Column("valor_glosa", sa.Numeric(), nullable=True),
        sa.Column("valor_liquido", sa.Numeric(), nullable=True),
        sa.Column("valor_restituicao", sa.Numeric(), nullable=True),
        sa.Column("ide_documento", sa.String(length=20), nullable=True),
        sa.Column("url_documento", sa.Text(), nullable=True),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["politico_id"], ["pol_politico.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pol_despesa_cota_ano"), "pol_despesa_cota", ["ano"], unique=False)
    op.create_index(
        op.f("ix_pol_despesa_cota_politico_id"), "pol_despesa_cota", ["politico_id"], unique=False
    )
    op.create_index(
        op.f("ix_pol_despesa_cota_resposta_id"), "pol_despesa_cota", ["resposta_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pol_despesa_cota_resposta_id"), table_name="pol_despesa_cota")
    op.drop_index(op.f("ix_pol_despesa_cota_politico_id"), table_name="pol_despesa_cota")
    op.drop_index(op.f("ix_pol_despesa_cota_ano"), table_name="pol_despesa_cota")
    op.drop_table("pol_despesa_cota")
    op.drop_index(op.f("ix_pol_pendencia_resposta_id"), table_name="pol_pendencia")
    op.drop_index(op.f("ix_pol_pendencia_cod_ibge"), table_name="pol_pendencia")
    op.drop_table("pol_pendencia")
    # ### end Alembic commands ###
