"""eventos do mandato (Câmara), vínculo de emendas e tipo de pendência

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-06 20:18:18.179992
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pol_evento_mandato",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("politico_id", sa.Integer(), nullable=False),
        sa.Column("data_hora", sa.DateTime(), nullable=False),
        sa.Column("legislatura", sa.Integer(), nullable=False),
        sa.Column("situacao", sa.String(length=60), nullable=True),
        sa.Column("condicao_eleitoral", sa.String(length=60), nullable=True),
        sa.Column("descricao_status", sa.Text(), nullable=True),
        sa.Column("partido", sa.String(length=30), nullable=True),
        sa.Column("url_fonte", sa.Text(), nullable=False),
        sa.Column("resposta_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["politico_id"], ["pol_politico.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resposta_id"],
            ["resposta_bruta.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pol_evento_mandato_politico_id"),
        "pol_evento_mandato",
        ["politico_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pol_evento_mandato_resposta_id"),
        "pol_evento_mandato",
        ["resposta_id"],
        unique=False,
    )
    op.add_column("pol_emenda", sa.Column("vinculo", sa.String(length=10), nullable=True))
    op.add_column("pol_emenda", sa.Column("nota_vinculo", sa.Text(), nullable=True))
    op.add_column(
        "pol_pendencia",
        sa.Column("tipo", sa.String(length=20), server_default="sem_eleito", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pol_pendencia", "tipo")
    op.drop_column("pol_emenda", "nota_vinculo")
    op.drop_column("pol_emenda", "vinculo")
    op.drop_index(op.f("ix_pol_evento_mandato_resposta_id"), table_name="pol_evento_mandato")
    op.drop_index(op.f("ix_pol_evento_mandato_politico_id"), table_name="pol_evento_mandato")
    op.drop_table("pol_evento_mandato")
    # ### end Alembic commands ###
